<a href="https://colab.research.google.com/github/fralfaro/MAT281/blob/main/docs/labs/lab_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# MAT281 - Laboratorio N°03



**Objetivo**: Aplicar técnicas avanzadas de manipulación y análisis de datos con pandas sobre un conjunto real de datos de contenido de Netflix, reforzando buenas prácticas y métodos eficientes sin recurrir a `groupby`, `merge`, `pivot`, ni `join`.



**Dataset**:

Trabajaremos con el archivo `netflix_titles.csv`, que contiene información sobre los títulos disponibles en la plataforma Netflix hasta el año 2021.

| Variable       | Clase     | Descripción                                                                 |
|----------------|-----------|------------------------------------------------------------------------------|
| show_id        | caracter  | Identificador único del título en el catálogo de Netflix.                   |
| type           | caracter  | Tipo de contenido: 'Movie' o 'TV Show'.                                     |
| title          | caracter  | Título del contenido.                                                       |
| director       | caracter  | Nombre del director (puede ser nulo).                                       |
| cast           | caracter  | Lista de actores principales (puede ser nulo).                              |
| country        | caracter  | País o países donde se produjo el contenido.                                |
| date_added     | fecha     | Fecha en la que el título fue agregado al catálogo de Netflix.              |
| release_year   | entero    | Año de lanzamiento original del título.                                     |
| rating         | caracter  | Clasificación por edad (por ejemplo: 'PG-13', 'TV-MA').                      |
| duration       | caracter  | Duración del contenido (minutos o número de temporadas para series).        |
| listed_in      | caracter  | Categorías o géneros en los que está clasificado el contenido.              |
| description    | caracter  | Breve sinopsis del contenido.                                               |

In [2]:
import pandas as pd

# Cargar datos
df = pd.read_csv('https://raw.githubusercontent.com/fralfaro/MAT281/main/docs/labs/data/netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...


### Parte 1: Limpieza y preparación

1. Revisar y describir el dataset:

   * ¿Cuántas filas y columnas tiene?
   * ¿Qué tipos de datos hay?
   * ¿Cuántos valores nulos hay por columna?

2. Transformar la columna `date_added` a tipo fecha.

3. Crear columnas auxiliares con `assign`:

   * Año (`year_added`)
   * Mes (`month_added`)

In [3]:
#FIXME
#1a)La cantidad de filas y columnas que tiene son
print("La cantidad de filas y columnas son:")
df.shape

La cantidad de filas y columnas son:

(8807, 12)

In [4]:
#1b)Los tipos de datos que tiene son
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [5]:
#1c)Datos nulos por columnas
df.nunique()

show_id         8807
type               2
title           8807
director        4528
cast            7692
country          748
date_added      1767
release_year      74
rating            17
duration         220
listed_in        514
description     8775
dtype: int64

In [6]:
#2)
import datetime
#Y eliminamos los espacios que tenga de mas (generan error al tener uno al comienzo) y dejando tambien los que no tienen fecha
df['date_added'] = df['date_added'].str.strip()
df['date_added'] = pd.to_datetime(df['date_added'])
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [7]:
#3) Vamos agregar 2 columnas nuevas con el año y el mes
df['year'] = df['date_added'].dt.year
df['month'] = df['date_added'].dt.month
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year,month
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,9.0

## Parte 2: Técnicas avanzadas de pandas

4. Utilizar `.loc` para seleccionar películas (`type == 'Movie'`) que fueron agregadas después del año 2018.

5. Utilizar `str.contains()` y `str.extract()`:

   * Filtrar títulos que contienen la palabra 'love' (sin distinguir mayúsculas/minúsculas).
   * Extraer la duración en minutos para las películas desde la columna `duration`.

6. Aplicar `explode()` sobre la columna `listed_in` para obtener una fila por cada género.

7. Obtener un top 10 de géneros más frecuentes utilizando `value_counts()`.

8. Aplicar `where()` y `mask()` para marcar las películas de más de 120 minutos como contenido largo en una nueva columna.

9. Utilizar `.loc` para filtrar películas que cumplen con:

   * Más de 100 minutos de duración.
   * Rating igual a `'R'`.
   * País igual a `'United States'`.

10. Utilizar `.style` para formatear visualmente el top 10 de películas más largas.

In [8]:
#FIXME
#4) Estan son las peliculas que salieron despues del año 2018
df_new = df.loc[df['year'] > 2018]
df_new.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year,month
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,9.0

In [9]:
#5)a) Filtramos todas las peliculas que tenga la palabra Love, suponiendo que son para todos los daños
df_a = df.loc[df['title'].str.contains('love', case=False)]
df_a.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year,month
25,s26,TV Show,Love on the Spectrum,NaN,Brooke Satchwell,Australia,2021-09-21,2021,TV-14,2 Seasons,"Docuseries, International TV Shows, Reality TV",Finding love can be hard for anyone. For young...,2021.0,9.0
158,s159,Movie,Love Don't Cost a Thing,Troy Byer,"Nick Cannon, Christina Milian, Kenan Thompson,...",United States,2021-09-01,2003,PG-13,101 min,"Comedies, Romantic Movies",A nerdy teen tries to make himself cool by ass...,2021.0,9.0
159,s160,Movie,Love in a Puff,Pang Ho-cheung,"Miriam Chin Wah Yeung, Shawn Yue, Singh Hartih...",Hong Kong,2021-09-01,2010,TV-MA,103 min,"Comedies, Dramas, International Movies",When the Hong Kong government enacts a ban on ...,2021.0,9.0
206,s207,Movie,"LSD: Love, Sex Aur Dhokha",Dibakar Banerjee,"Nushrat Bharucha, Anshuman Jha, Neha Chauhan, ...",India,2021-08-27,2010,TV-MA,112 min,"Dramas, Independent Movies, International Movies",This provocative drama examines how the voyeur...,2021.0,8.0
227,s228,Movie,Really Love,Angel Kristi Williams,"Kofi Siriboe, Yootha Wong-Loi-Sing, Michael Ea...",United States,2021-08-25,2020,TV-MA,95 min,"Dramas, Independent Movies, Romantic Movies",A rising Black painter tries to break into a c...,2021.0,8.0

In [10]:
df_a = df.loc[df['type'].str.contains('Movie', case=False)]
df_a.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year,month
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,2021-09-24,2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,2021.0,9.0
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",2021.0,9.0
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,2021.0,9.0
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",2021-09-23,2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...,2021.0,9.0

In [11]:
#5)b) Se mostrar todas las prliculas y los minutos que dura
df_b = df.loc[df['type'].str.contains('Movie', case=False)]
df_movie = df_b[['title']].copy()
df_movie['Min'] = df['duration'].str.extract(r'(\d+)').fillna(0).astype(int)
df_movie.head(100)

                                title  Min
0                Dick Johnson Is Dead   90
6    My Little Pony: A New Generation   91
7                             Sankofa  125
9                        The Starling  104
12                       Je Suis Karl  127
..                                ...  ...
157                          Level 16  102
158           Love Don't Cost a Thing  101
159                    Love in a Puff  103
161                     Mars Attacks!  106
162                          Marshall  118

[100 rows x 2 columns]

In [12]:
df['listed_in'] = df['listed_in'].str.split(', ')
df_e = df['listed_in'].explode('listed_in')
df_e = df_e.drop_duplicates()
df_e.head(10)

0              Documentaries
1     International TV Shows
2                  TV Dramas
3               TV Mysteries
4             Crime TV Shows
6      TV Action & Adventure
7                 Docuseries
8                 Reality TV
10         Romantic TV Shows
11               TV Comedies
Name: listed_in, dtype: object

In [13]:
df_op = df.explode('listed_in')
df_unu = df_op['listed_in'].value_counts()
df_unu.head(10)

listed_in
International Movies        2752
Dramas                      2427
Comedies                    1674
International TV Shows      1351
Documentaries                869
Action & Adventure           859
TV Dramas                    763
Independent Movies           756
Children & Family Movies     641
Romantic Movies              616
Name: count, dtype: int64

In [14]:
df_movie['Largo o corto'] = df_movie['Min'].where( df_movie['Min'] <=120, 'Largo').mask( df_movie['Min'] <=120, 'Corto')

df_movie.head()

                               title  Min Largo o corto
0               Dick Johnson Is Dead   90         Corto
6   My Little Pony: A New Generation   91         Corto
7                            Sankofa  125         Largo
9                       The Starling  104         Corto
12                      Je Suis Karl  127         Largo

In [15]:
df_juju = df.loc[df['type'].str.contains('Movie', case=False)].copy()
df_juju['duration'] = df['duration'].str.extract(r'(\d+)').fillna(0).astype(int)
df_juju = df_juju.loc[(df_juju['duration']>=100)&(df_juju['rating']=='R')&(df_juju['country']=='United States')]
df_juju.head(100)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year,month
48,s49,Movie,Training Day,Antoine Fuqua,"Denzel Washington, Ethan Hawke, Scott Glenn, T...",United States,2021-09-16,2001,R,122,"[Dramas, Thrillers]",A rookie cop with one day to prove himself to ...,2021.0,9.0
81,s82,Movie,Kate,Cedric Nicolas-Troyan,"Mary Elizabeth Winstead, Jun Kunimura, Woody H...",United States,2021-09-10,2021,R,106,[Action & Adventure],"Slipped a fatal poison on her final job, a rut...",2021.0,9.0
131,s132,Movie,Blade Runner: The Final Cut,Ridley Scott,"Harrison Ford, Rutger Hauer, Sean Young, Edwar...",United States,2021-09-01,1982,R,117,"[Action & Adventure, Classic Movies, Cult Movies]","In a smog-choked dystopian Los Angeles, blade ...",2021.0,9.0
139,s140,Movie,Do the Right Thing,Spike Lee,"Danny Aiello, Ossie Davis, Ruby Dee, Richard E...",United States,2021-09-01,1989,R,120,"[Classic Movies, Comedies, Dramas]","On a sweltering day in Brooklyn, simmering rac...",2021.0,9.0
144,s145,Movie,House Party,Reginald Hudlin,"Christopher Reid, Christopher Martin, Robin Ha...",United States,2021-09-01,1990,R,104,"[Comedies, Cult Movies]","Grounded by his strict father, Kid risks life ...",2021.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2704,s2705,Movie,The Florida Project,Sean Baker,"Brooklynn Prince, Bria Vinaite, Willem Dafoe, ...",United States,2020-04-06,2017,R,111,"[Dramas, Independent Movies]",A mischievous 6-year-old finds the magic in he...,2020.0,4.0
2707,s2708,Movie,Angel Has Fallen,Ric Roman Waugh,"Gerard Butler, Morgan Freeman, Nick Nolte, Dan...",United States,2020-04-04,2019,R,121,[Action & Adventure],Secret Service agent Mike Banning is caught in...,2020.0,4.0
2745,s2746,Movie,The Runaways,Floria Sigismondi,"Kristen Stewart, Dakota Fanning, Michael Shann...",United States,2020-04-01,2010,R,107,"[Dramas, Independent Movies, Music & Musicals]",This biopic charts the rise of the rebellious ...,2020.0,4.0
2762,s2763,Movie,Rogue Warfare,Mike Gunther,"Will Yun Lee, Jermaine Love, Rory Markham, Ber...",United States,2020-03-28,2019,R,103,[Action & Adventure],An elite international squad of uniquely skill...,2020.0,3.0
2779,s2780,Movie,Crip Camp: A Disability Revolution,NaN,NaN,United States,2020-03-25,2020,R,108,[Documentaries],A groundbreaking summer camp galvanizes a grou...,2020.0,3.0

In [16]:
df_lol = df.loc[df['type'].str.contains('Movie', case=False)].copy()
df_lol['duration'] = df['duration'].str.extract(r'(\d+)').fillna(0).astype(int)
df_lol = df_lol.sort_values('duration', ascending = False)
df_lol.head(10).style



### Pregunta Desafío

11. ¿Cuáles son las combinaciones más frecuentes de género y rating en el dataset?
    (Sugerencia: utilizar `value_counts` con `subset=["genre", "rating"]` después de aplicar `explode()`).



### Bonus: Análisis de duplicados y limpieza

12. ¿Existen películas con el mismo nombre (`title`) pero con distinto año de lanzamiento (`release_year`)?
13. ¿Cuántos títulos únicos hay en total en la columna `title`?

In [17]:
#FIXME
df_op = df.explode('listed_in')
df_rg= df_op.value_counts(subset=['listed_in', 'rating'])
print(df_rg)

listed_in               rating
International Movies    TV-MA       1130
                        TV-14       1065
Dramas                  TV-MA        830
International TV Shows  TV-MA        714
Dramas                  TV-14        693
                                    ...
TV Sci-Fi & Fantasy     NR             1
TV Mysteries            TV-G           1
TV Sci-Fi & Fantasy     TV-Y7-FV       1
TV Shows                R              1
Action & Adventure      G              1
Name: count, Length: 309, dtype: int64

In [18]:
df_movie = df[df['type'].str.contains('Movie', case=False)]
df_dupl = df_movie['title'].duplicated(keep=False)
result = df_movie[df_dupl].sort_values(by=['title','release_year'])
print("peliculas con el mismo nombre y distinto año de lanzamiento:")
print(result)

peliculas con el mismo nombre y distinto año de lanzamiento:
Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description, year, month]
Index: []

In [19]:
#Los titulos unicos que hay en la columna
df['title'].nunique()

8807